django_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("polls/", include("polls.urls")),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path(
        "question/",
        views.QuestionListView.as_view(),
        name="question-list"
    ),
    path(
        "question/<int:pk>",
        views.QuestionDetailView.as_view(),
        name="question-detail"
    ),
    path(
        "question/create",
        views.QuestionCreateView.as_view(),
        name="question-create"
    ),
    path(
        "question/<int:pk>/update",
        views.QuestionUpdateView.as_view(),
    ),

    path(
        "choice/",
        views.ChoiceListView.as_view(),
        name="choice-list"
    ),
    path(
        "choice/<int:pk>",
        views.ChoiceDetailView.as_view(),
        name="choice-detail"
    ),
    path(
        "choice/create",
        views.ChoiceCreateView.as_view(),
        name="choice-create"
    ),
    path(
        "choice/<int:pk>/update",
        views.ChoiceUpdateView.as_view(),
    ),
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponse
from django.views.generic import (ListView, DetailView)
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from .models import Question, Choice
from django.urls import reverse_lazy


def index(request):
    return HttpResponse("Hello world. You're at the polls index.")


class QuestionListView(ListView):
    model = Question
    queryset = Question.objects.all().order_by("-pub_date")

class QuestionDetailView(DetailView):
    model = Question

class QuestionCreateView(UpdateView):
    model = Question
    fields = ["question_text", "pub_date"]
    success_url = reverse_lazy("question-list")

class QuestionUpdateView(UpdateView):
    model = Question
    fields = ["question_text", "pub_date"]

    def get_success_url(self) -> str:
        return reverse_lazy(
            "question-detail",
            kwargs={"pk": self.object.id}
        )

class QuestionDeleteView(DeleteView):
    model = Question
    success_url = reverse_lazy("question-list")


class ChoiceListView(ListView):
    model = Choice
    queryset = Choice.objects.all()

class ChoiceDetailView(DetailView):
    model = Choice

class ChoiceCreateView(CreateView):
    model = Choice
    fields = ["question", "choice_text", "votes"]
    success_url = reverse_lazy("choice-list")

class ChoiceUpdateView(UpdateView):
    model = Choice
    fields = ["choice_text", "votes"]

    def get_success_url(self) -> str:
        return reverse_lazy(
            "choice-detail",
            kwargs={"pk": self.object.id}
        )

class ChoiceDeleteView(DeleteView):
    model = Choice
    success_url = reverse_lazy("choice-list")

polls/templates/choices/base.html
{% load static %} 

<!DOCTYPE html>
<head>
   <meta charset="UTF-8">
   <title>Мой блог</title>
   <link rel="stylesheet" href="{% static 'css/diary.css' %}"> 
</head>
<body>
   <h1><a href="/">Привет, читатель!</a></h1> 
   {% block content %}{% endblock %}
</body>
</html>

polls/templates/choices/choice_detail.html
<article>
    <h3>{{ choice.question }}</h3>
    <p>{{ choice.votes }}</p>
 </article>

 <p>
    <a href="{% url 'choice-update' choice.id %}">Редактировать</a> 
    <a href="{% url 'choice-delete' choice.id %}">Удалить</a> 
</p>

polls/templates/choices/choice_form.html
{% extends "choices/base.html" %} 
{% block content %}
   <form method="post">
         {% csrf_token %}
       {{ form.as_p }} 
       <input type="submit" value="Сохранить">
   </form>
   {% if question %}
       <a href="{% url 'choice-detail' choice.id %}">
           <button>Отмена</button>
       </a>
   {% else %}
       <a href="{% url 'choice-list' %}">
           <button>Отмена</button>
       </a>
   {% endif %}
{% endblock %}

polls/templates/choices/choice_list.html
{% for question in question_list %} 
<article>
   <h2 class="{{ choice.question }}">
       {{ choice.question }}
   </h2>
   <h3>
       <a href="{% url 'choice-detail' choice.id %}">
           {{ choice.title }}
       </a>
   </h3>
{% endfor %}
<article>
    <h2 class="mark">{% now "Y-m-d H:i" %}</em></h2>
    <a href="{% url 'choice-create' %}"><button>Добавить новую запись</button></a> 
 </article>

polls/templates/choices/choice_update_form.html
{% extends "choices/base.html" %} 
{% block content %}
   <form method="post">
         {% csrf_token %}
       {{ form.as_p }} 
       <input type="submit" value="Сохранить">
   </form>
   {% if choice %}
       <a href="{% url 'choice-detail' choice.id %}">
           <button>Отмена</button>
       </a>
   {% else %}
       <a href="{% url 'choice-list' %}">
           <button>Отмена</button>
       </a>
   {% endif %}
{% endblock %}

polls/templates/questions/base.html
{% load static %} 

<!DOCTYPE html>
<head>
   <meta charset="UTF-8">
   <title>Мой блог</title>
   <link rel="stylesheet" href="{% static 'css/diary.css' %}"> 
</head>
<body>
   <h1><a href="/">Привет, читатель!</a></h1> 
   {% block content %}{% endblock %}
</body>
</html>

polls/templates/questions/question_detail.html
<article>
    <h2>{{ question.pub_date|date:'Y-m-d H:i' }}</h2> 
    <h3>{{ question.question_text }}</h3> 
 </article>

 <p>
    <a href="{% url 'question-update' question.id %}">Редактировать</a> 
    <a href="{% url 'question-delete' question.id %}">Удалить</a> 
</p>

polls/templates/questions/question_form.html
{% extends "questions/base.html" %} 
{% block content %}
   <form method="post">
         {% csrf_token %}
       {{ form.as_p }} 
       <input type="submit" value="Сохранить">
   </form>
   {% if question %}
       <a href="{% url 'question-detail' question.id %}">
           <button>Отмена</button>
       </a>
   {% else %}
       <a href="{% url 'question-list' %}">
           <button>Отмена</button>
       </a>
   {% endif %}
{% endblock %}

polls/templates/questions/question_list.html
{% for question in question_list %} 
<article>
   <h2 class="{{ question.pub_date|date:'l' }}">
       {{ question.pub_date|date:'Y-m-d H:i' }}
   </h2>
   <h3>
       <a href="{% url 'question-detail' question.id %}">
           {{ question.title }}
       </a>
   </h3>
{% endfor %}
<article>
    <h2 class="mark">{% now "Y-m-d H:i" %}</em></h2>
    <a href="{% url 'question-create' %}"><button>Добавить новую запись</button></a> 
 </article>

polls/templates/questions/question_update_form.html
{% extends "questions/base.html" %} 
{% block content %}
   <form method="post">
         {% csrf_token %}
       {{ form.as_p }} 
       <input type="submit" value="Сохранить">
   </form>
   {% if question %}
       <a href="{% url 'question-detail' question.id %}">
           <button>Отмена</button>
       </a>
   {% else %}
       <a href="{% url 'question-list' %}">
           <button>Отмена</button>
       </a>
   {% endif %}
{% endblock %}